language: cpp
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq gperf libasio-dev libboost-dev libc-ares-dev libdb++-dev libpopt-dev libssl-dev perl libmysqlclient-dev libfreeradius-client-dev libcppunit-dev autotools-dev libpcre3-dev libxerces-c-dev curl libcajun-dev python-cxx-dev libsipxtapi-dev libsrtp-dev
 - sudo add-apt-repository -y "deb http://http.debian.net/debian/ sid main"
 - sudo apt-get update -qq
 - sudo apt-get install -qq --force-yes libfreeradius-client-dev libcajun-dev libsipxtapi-dev
 - ./build/travis/coverity-setup
compiler:
  - gcc
  - clang
script:
  - ./build/travis/bootstrap
  - ./build/travis/configure
  - ./build/travis/build
